name: Build/Test Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: self-hosted
    steps:
    - name: PR Validator
      uses: santomegonzalo/pr-checker-github-action@v1
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        jira_title_regex: ^\[(([A-Z][A-Z0-9]+-[0-9]+)|NOJIRA)\]
        required_labels: "feature,bug,documentation,chore"
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Run tests with Gradle Wrapper
      run: ./gradlew jacocoTestReport
