name: Build/Test Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: self-hosted
    steps:
    - name: PR Validator
      uses: sainath-turtlemint/pr-validator@v1.6
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Run tests with Gradle Wrapper
      run: ./gradlew jacocoTestReport
